# Generated by Django 5.1.7 on 2025-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_alter_assignmentsubmission_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='video',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='subject',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
